#version: "3.3"

services:
  jupyter:
    # you can change this to whatever you want.
    container_name: torchganime
    build:
      context: ./
      dockerfile: ./Dockerfile
      shm_size: '100gb'
    shm_size: '100gb'
    volumes:
      - "./:/TorchGANime"
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
