# ckpt_path: null

trainer:
  accelerator: "gpu"
  devices: 
    # - 0
    # - 1
    # - 2
    # - 3
    - 4
    - 5
    - 6
    - 7
  accumulate_grad_batches: 5
  precision: 16
model:
  learning_rate: 4.5e-5
  autoencoder_config:
    embed_dim: 256
    n_embed: 1024
    channels: 128
    z_channels: 256
    resolution: 256
    in_channels: 3
    out_channels: 3
    ch_mult: [1, 1, 2, 2, 4]
    n_res_blocks: 1
    attn_resolutions: [16]
    dropout: 0.0
    resamp_with_conv: True
  
  loss_config:
    disc_channels: 64
    disc_n_layers: 3
    disc_use_actnorm: False
    disc_start: 30001
    disc_factor: 1.0
    disc_weight: 0.8
    codebook_weight: 1.0
    pixelloss_weight: 1.0
    perceptual_weight: 1.0
    disc_loss: "hinge"

data:
  path: "./data/kny/images/01"
  batch_size: 2
  num_workers: 4
  image_size: 
    - 256 
    - 512
