seed_everything: true
trainer:
  devices:
  - 0
  - 1
  - 2
  - 3
  # - 4
  # - 5
  # - 6
  # - 7
  accumulate_grad_batches: 5
  accelerator: gpu
  precision: 16
  gradient_clip_val: 1.0
model:
  learning_rate: 4.5e-5
  autoencoder_config:
    embed_dim: 256
    n_embed: 50257
    channels: 256
    z_channels: 256
    resolution: 256
    in_channels: 3
    out_channels: 3
    ch_mult:
    - 1
    - 1
    - 2
    - 2
    # - 4
    n_res_blocks: 2
    attn_resolutions:
      - 32
    dropout: 0.1
    resamp_with_conv: True
  loss_config:
    disc_channels: 64
    disc_n_layers: 2
    disc_use_actnorm: True
    disc_start: 10000
    disc_factor: 1.0
    disc_weight: 0.8
    codebook_weight: 1.0
    pixelloss_weight: 1.0
    perceptual_weight: 1.0
    disc_loss: hinge

data:
  path: "./data/kny/images/01"
  batch_size: 2
  num_workers: 1
  image_size: 
    - 128 
    - 256