seed_everything: true
trainer:
  devices:
  - 0
  - 1
  - 2
  - 3
  accumulate_grad_batches: 5
  accelerator: gpu
  precision: 16
  gradient_clip_val: 1.0
  limit_train_batches: 1000
  limit_val_batches: 100
  # strategy: deepspeed_stage_3
model:
  learning_rate: 3e-4
  vqgan_ckpt_path: "/TorchGANime/checkpoints/vqgan_full/checkpoints/epoch=199-step=168800.ckpt"
  transformer_ckpt_path: "gpt2"
  use_position_embeddings: True
data:
  train_paths: 
    - "/TorchGANime/data/*/raw_videos/*0.mkv"
    - "/TorchGANime/data/*/raw_videos/*1.mkv"
    - "/TorchGANime/data/*/raw_videos/*2.mkv"
    - "/TorchGANime/data/*/raw_videos/*3.mkv"
    - "/TorchGANime/data/*/raw_videos/*4.mkv"
    - "/TorchGANime/data/*/raw_videos/*5.mkv"
    - "/TorchGANime/data/*/raw_videos/*6.mkv"
    - "/TorchGANime/data/*/raw_videos/*7.mkv"
    - "/TorchGANime/data/*/raw_videos/*8.mkv"
  val_paths:
    - "/TorchGANime/data/*/raw_videos/*9.mkv"
  batch_size: 3
  num_workers: 16
  image_size: 
    - 128 
    - 256