seed_everything: true
trainer:
  devices:
  - 1
  accumulate_grad_batches: 16
  accelerator: gpu
  precision: 16
  gradient_clip_val: 1.0
  # limit_train_batches: 1000
  limit_val_batches: 100
  # strategy: deepspeed_stage_3
model:
  learning_rate: 5e-4
  vqgan_ckpt_path: "/TorchGANime/checkpoints/vqgan_full/checkpoints/checkpoint.ckpt"
  transformer_ckpt_path: "gpt2"
  use_token_type_ids: True
  rec_loss_weight: 1.0
  perceptual_loss_weight: 1.0
data:
  train_paths: 
    # - "/TorchGANime/data/*/raw_videos/01.mkv"
    - "/TorchGANime/data/*/raw_videos/02.mkv"
    # - "/TorchGANime/data/*/raw_videos/*0.mkv"
    # - "/TorchGANime/data/*/raw_videos/*1.mkv"
    # - "/TorchGANime/data/*/raw_videos/*2.mkv"
    # - "/TorchGANime/data/*/raw_videos/*3.mkv"
    # - "/TorchGANime/data/*/raw_videos/*4.mkv"
    # - "/TorchGANime/data/*/raw_videos/*5.mkv"
    # - "/TorchGANime/data/*/raw_videos/*6.mkv"
    # - "/TorchGANime/data/*/raw_videos/*7.mkv"
    # - "/TorchGANime/data/*/raw_videos/*8.mkv"
  val_paths:
    - "/TorchGANime/data/kny/raw_videos/02.mkv"
  batch_size: 8
  num_workers: 16
  image_size: 
    - 128 
    - 256