seed_everything: true
trainer:
  devices:
  - 0
  - 1
  - 2
  - 3
  accumulate_grad_batches: 4
  accelerator: gpu
  precision: 16
  gradient_clip_val: 1.0
  # limit_train_batches: 1000
  limit_val_batches: 100
  # strategy: deepspeed_stage_3
  max_epochs: -1
model:
  learning_rate: 5e-4
  vqgan_ckpt_path: "/TorchGANime/checkpoints/vqgan_full/checkpoints/checkpoint.ckpt"
  transformer_ckpt_path: "gpt2-medium"
  use_token_type_ids: False
  rec_loss_weight: 0.0
  perceptual_loss_weight: 0.0
data:
  train_paths: 
    # - "/TorchGANime/data/*/raw_videos/01.mkv"
    # - "/TorchGANime/data/*/raw_videos/02.mkv"
    # - "/TorchGANime/data/*/raw_videos/03.mkv"
    - "/TorchGANime/data/*/raw_videos/10.mkv"
    - "/TorchGANime/data/*/raw_videos/20.mkv"
    # - "/TorchGANime/data/*/raw_videos/*1.mkv"
    # - "/TorchGANime/data/*/raw_videos/*2.mkv"
    # - "/TorchGANime/data/*/raw_videos/*3.mkv"
    # - "/TorchGANime/data/*/raw_videos/*4.mkv"
    # - "/TorchGANime/data/*/raw_videos/*5.mkv"
    # - "/TorchGANime/data/*/raw_videos/*6.mkv"
    # - "/TorchGANime/data/*/raw_videos/*7.mkv"
    # - "/TorchGANime/data/*/raw_videos/*8.mkv"
  val_paths:
    # - "/TorchGANime/data/*/raw_videos/*9.mkv"
    - "/TorchGANime/data/*/raw_videos/01.mkv"
  batch_size: 1
  num_workers: 4
  image_size: 
    - 128 
    - 256