seed_everything: true
trainer:
  devices:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  accumulate_grad_batches: 24
  accelerator: gpu
  # precision: 16
  gradient_clip_val: 1.0
  strategy: ddp
model:
  learning_rate: 5e-4
  autoencoder_config:
    embed_dim: 128
    n_embed: 1024
    channels: 32
    z_channels: 512
    resolution: 256
    in_channels: 3
    out_channels: 3
    ch_mult:
    - 2
    - 4
    - 8
    - 8
    # - 4
    n_res_blocks: 1
    attn_resolutions:
      - 16
    dropout: 0.0
    resamp_with_conv: True
  loss_config:
    disc_channels: 64
    disc_n_layers: 3
    disc_use_actnorm: False
    disc_start: 10000
    disc_factor: 1.0
    disc_weight: 0.8
    codebook_weight: 1.0
    pixelloss_weight: 1.0
    perceptual_weight: 1.0
    disc_loss: hinge

data:
  path: "/TorchGANime/data/full"
  batch_size: 16
  num_workers: 8
  image_size: 
    - 128 
    - 256